version: '3'
services:
  mynodered:
    image: "nodered/node-red:${ARCHITECTUR}"
    container_name: mynodered
    build:
      context: .
      args:
        ROS_DIST: ${ROSVERSION}
        PLATFORM: ${ARCHITECTUR}
      dockerfile: Dockerfile-nodered
    ports:
      - "1880:1880"
      - "9099:9099"
      - "9090:9090"
    volumes:
      - "../container-exchange/.node-red:/data"
      - "../container-exchange/controll:/controll"
      - "../container-exchange/node-red-contrib-web-babylonjs/.:/usr/src/node-red/node_modules/node-red-contrib-web-babylonjs/."
