version: '3'
services:
  graphicnodered:
    image: "nodered/node-red:${ARCHITECTUR}"
    build:
      context: .
      dockerfile: Dockerfile-nodered
      args:
        PLATFORM: ${ARCHITECTUR}
    volumes:
      - ".docker-exchange/.node-red:/data"
    ports:
      - "1880:1880"
      - "9099:9099"
  myroscore:
    image: "roscore/${ARCHITECTUR}:${ROSVERSION}"
    build:
      context: .
      args:
        ROS_DIST: ${ROSVERSION}
        PLATFORM: ${ARCHITECTUR}
      dockerfile: Dockerfile-roscore
    ports:
      - "11311:11311"
      - "9090:9090"
  #myroscore_arm64:
  #  image: roscore/arm64:melodic
  #  build:
  #    context: .
  #    dockerfile: Dockerfile-roscore-arm64
  #  ports:
  #    - "11311:11311"
  #    - "9090:9090"
