FROM --platform=linux/arm64 ros:melodic-ros-core-stretch
RUN mkdir /data && \
    apt-get update  && \
    apt-get install -y \
    ros-melodic-rosbridge-server \
    python-twisted \
    python-rosdep python-rosinstall python-rosinstall-generator python-wstool \
    python-pip && \
    pip install twisted pyOpenSSL autobahn tornado pymongo

RUN /bin/bash -c "source /opt/ros/melodic/setup.bash; rosdep install -y rosbridge_server; "


#CMD [ "roscore" ]
CMD [ "roslaunch", "rosbridge_server", "rosbridge_websocket.launch" ]
