ARG PLATFORM
ARG ROS_DIST
FROM --platform=linux/$PLATFORM ros:$ROS_DIST-ros-core-stretch

ARG ROS_DIST

#COPY ros-entery.sh /src/ros-entery.sh
#COPY entery-files/ros-entery.sh /src/ros-entery.sh

RUN export CHOOSE_ROS_DISTRO=${ROS_DIST} && \
    mkdir /data && \
    apt-get update && \
    apt-get install -y \
    python-twisted \
    python-rosdep python-rosinstall python-rosinstall-generator python-wstool \
    python-cffi \
    libffi-dev \
    python-pip 
RUN pip install twisted pyOpenSSL autobahn tornado pymongo && \
    #/bin/bash -c "source /opt/ros/${CHOOSE_ROS_DISTRO}/setup.bash; rosdep install -y rosbridge_server; " && \
    mkdir /src 
RUN echo "" > rosbase-entery.sh && \
    chmod +x rosbase-entery.sh

COPY ./rosbase-entery.sh rosbase-entery.sh

#CMD [ "roscore" ]
#CMD [ "/bin/bash", "-c", "'source /opt/ros/${CHOOSE_ROS_DISTRO}/setup.bash; /src/ros-entery.sh;'" ]
CMD bash -C '/ros-entery.sh';'bash'
