version: '3'
services:
  myinterface:
    image: "myinterface/${ARCHITECTUR}:${ROSVERSION}"
    container_name: myinterface
    build:
      context: .
      args:
        ROS_DIST: ${ROSVERSION}
        PLATFORM: ${ARCHITECTUR}
      dockerfile: Dockerfile-udpros
    ports:
      - "8002:8002/udp"
      - "8001:8001/udp"
      - "8000:8000/udp"
      - "4210:4210/udp"
    expose:
      - "11311"
    environment:
      - ROS_MASTER_URI=http://${WIFIIP}:11311
    volumes:
      - "../container-exchange/.node-red:/data"
      - "../container-exchange/src:/src"
      - "../container-exchange/lib:/src/lib"
      - "../container-exchange/usr/games:/usr/games"
