ARG PLATFORM
ARG ROS_DIST
FROM rosbase/$PLATFORM:$ROS_DIST

COPY ./ros-entery.sh ./ros-entery.sh

RUN echo "deb http://ports.ubuntu.com/ubuntu-ports bionic main" >> /etc/apt/sources.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32 && \
    apt-get update && \
    apt-get install -y libboost-all-dev \
    libffi-dev \
    libyaml-cpp-dev \
    libalglib-dev

CMD bash -C './ros-entery.sh';'bash'
