version: '3'
services:
  bionic_base:
    image: bionic/${ARCHITECTUR}:latest
    build: .
  bionic_ros:
    image: bionic/${ARCHITECTUR}:${ROSVERSION}
    volumes:
      - /home/$USER/Projects:/home/userdev/Projects
    build:
      context: .
      dockerfile: Dockerfile-ros
      args:
        DOCKER_VAR_ROS_DISTRO: ${ROSVERSION}
